packages:
  - '.'
  - 'apps/*'
  - 'packages/*'
virtualStoreDir: '.pnpm'
virtualStoreDirMaxLength: 40
packageImportMethod: 'hardlink'
nodeLinker: 'hoisted'
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - 'esbuild'
  - 'unrs-resolver'
